/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux ec-ubuntu-14-04-x86-64-2 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"
#define CXX "c++"
#define COMPILER "/usr/bin/c++"
#define COMPILERVERS "c++"
#define MAKESHAREDLIB  "cd $BuildDir ; c++ -c $Opt -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles ; c++ $ObjectFiles -shared  $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; c++ -c  -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles; c++ $ObjectFiles  -o $ExeName $LinkedLibs -lm -ldl -lpthread -rdynamic"
#define CXXOPT ""
#define CXXDEBUG "-O2 -DNDEBUG"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o"
#define SOEXT "so"
