# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, /mnt/vdb/lsf/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/sources/root_v5.34.34/root)
ROOT_OBJDIR    := $(call realpath, /mnt/vdb/lsf/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v5.34.34-cmake)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

ARCH           := linuxx8664gcc
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := -v 5 34 34 

EXTRA_CFLAGS   := -Iinclude  -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations
USERCONF_CFLAGS:= 
EXTRA_CXXFLAGS := -Iinclude  -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations
USERCONF_CXXFLAGS:= 
EXTRA_LDFLAGS  := 
WERROR         := 
WINRTDEBUG     := no

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man
DATADIR        := $(ROOTSYS)/.
ELISPDIR       := $(ROOTSYS)/emacs/site-lisp
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := $(ROOTSYS)/src
ICONPATH       := $(ROOTSYS)/icons
CINTINCDIR     := $(ROOTSYS)/cint
DOCDIR         := $(ROOTSYS)/.
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/aclocal

BUILDX11       := yes
X11INCDIR      := $(filter-out /usr/include, )
X11LIBDIR      := -L/usr/lib/x86_64-linux-gnu
XPMLIBDIR      := -L/usr/lib/x86_64-linux-gnu
XPMLIB         := /usr/lib/x86_64-linux-gnu/libXpm.so
XFTLIB         := yes

BUILDCOCOA     := 
MACOSXVERS     := 
OSXSDK         := 
IOSVERS        := 
IOSSDK         := 

CXX11          := 
CXX14          := 
LIBCXX         := 

EXPLICITLINK   := yes

ENABLETHREAD   := yes
OSTHREADFLAG   := -pthread
OSTHREADLIBDIR := 
OSTHREADLIB    := -lpthread

BUILTINFREETYPE:= yes

BUILTINPCRE    := yes

BUILTINZLIB    := no
ZLIBLIBDIR     := 
ZLIBCLILIB     := /usr/lib/x86_64-linux-gnu/libz.so
ZLIBINCDIR     := $(filter-out /usr/include, /usr/include)

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

BUILDGL        := yes
OPENGLLIBDIR   := 
OPENGLULIB     := /usr/lib/x86_64-linux-gnu/libGLU.so
OPENGLLIB      := /usr/lib/x86_64-linux-gnu/libGL.so
OPENGLINCDIR   := $(filter-out /usr/include, /usr/include)

BUILDLDAP      := no
LDAPLIBDIR     := 
LDAPCLILIB     := LDAP_LIBRARY-NOTFOUND
LDAPINCDIR     := $(filter-out /usr/include, LDAP_INCLUDE_DIR-NOTFOUND)

BUILDMYSQL     := yes
MYSQLLIBDIR    := 
MYSQLCLILIB    := 
MYSQLINCDIR    := $(filter-out /usr/include, /usr/include/mysql)

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   := ORACLE_LIBRARY_OCCI-NOTFOUND ORACLE_LIBRARY_CLNTSH-NOTFOUND ORACLE_LIBRARY_LNNZ-NOTFOUND
ORACLEINCDIR   := $(filter-out /usr/include, ORACLE_INCLUDE_DIR-NOTFOUND)

BUILDPGSQL     := no
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSQLITE     := no
SQLITELIBDIR    := 
SQLITECLILIB    := 
SQLITEINCDIR    := $(filter-out /usr/include, SQLITE_INCLUDE_DIR-NOTFOUND)

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDQT        := yes
BUILDQTGSI     := 
QTLIBDIR       := /usr/lib/x86_64-linux-gnu
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, /usr/include/qt4)
QTVERS	       := 4
QTMOCEXE       := /usr/lib/x86_64-linux-gnu/qt4/bin/moc

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, CASTOR_INCLUDE_DIR-NOTFOUND)
CASTORCFLAGS   := 

BUILDDAVIX      := no
DAVIXLIBDIR     := 
DAVIXCLILIB     := 
DAVIXINCDIR     := $(filter-out /usr/include, )

BUILDDCAP      := 
DCAPLIBDIR     := 
DCAPLIB        := DCAP_LIBRARY-NOTFOUND
DCAPINCDIR     := $(filter-out /usr/include, DCAP_INCLUDE_DIR-NOTFOUND)

BUILDFTGL      := yes
FTGLLIBDIR     := 
FTGLLIBS       := FTGL
FTGLINCDIR     := $(filter-out /usr/include, /mnt/vdb/lsf/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/sources/root_v5.34.34/root/graf3d/ftgl/inc)
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := yes
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := no
GFALLIBDIR     := 
GFALCLILIB     := 
GFALINCDIR     := $(filter-out /usr/include, GFAL_INCLUDE_DIR-NOTFOUND)
SRMIFCEINCDIR  := $(filter-out /usr/include, )
GLIB2INCDIR    := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := yes

BUILDBONJOUR   := yes
DNSSDLIBDIR    := 
DNSSDLIB       := /usr/lib/x86_64-linux-gnu/libdns_sd.so
DNSSDINCDIR    := $(filter-out /usr/include, )
BONJOURCPPFLAGS := 

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS      := no
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )
JNIINCDIR      := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB      := 
JVMLIBDIR      := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := ALIEN_LIBRARY-NOTFOUND
ALIENINCDIR    := $(filter-out /usr/include, ALIEN_INCLUDE_DIR-NOTFOUND)

BUILDASIMAGE   := yes
BUILTINASIMAGE := ON
ASEXTRALIB     := /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so
ASEXTRALIBDIR  := 
ASJPEGINCDIR   := $(filter-out /usr/include, JPEG_INCLUDE_DIR-NOTFOUND)
ASPNGINCDIR    := $(filter-out /usr/include, /usr/include)
ASTIFFINCDIR   := $(filter-out /usr/include, TIFF_INCLUDE_DIR-NOTFOUND)
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := PYTHIA6_LIBRARY-NOTFOUND
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := yes
FPYTHIA8INCDIR   := $(filter-out /usr/include, )
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := /opt/pythia8/lib/libpythia8.so

BUILDFFTW3     := yes
FFTW3LIBDIR    := 
FFTW3LIB       := /usr/lib/x86_64-linux-gnu/libfftw3.so
FFTW3INCDIR    := $(filter-out /usr/include, /usr/include)

BUILDFITSIO    := yes
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := yes
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := yes
PYTHONLIBDIR   := 
PYTHONLIB      := /usr/lib/x86_64-linux-gnu/libpython2.7.so
PYTHONINCDIR   := $(filter-out /usr/include, /usr/include/python2.7)
PYTHONLIBFLAGS := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := yes
XMLLIBDIR      := 
XMLCLILIB      := /usr/lib/x86_64-linux-gnu/libxml2.so
XMLINCDIR      := $(filter-out /usr/include, /usr/include/libxml2)

HASXRD         := 
XRDINCDIR      := 
XRDLIBDIR      := 
EXTRA_XRDFLAGS := 
XRDVERSION     := 
HASXRDUTILS    := 
XRDINCPRIVATE  := 
BUILDNETXNG    := yes
BUILDXPROOFD   := 
BUILDXRDCLT    := 

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := yes
KRB5LIB        := /usr/lib/x86_64-linux-gnu/libkrb5.so
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, /usr/include/krb5)
KRB5INIT       := KRB5_INIT-NOTFOUND

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := -lcrypt
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := MONALISA_LIBRARY-NOTFOUND
MONALISAINCDIR := $(filter-out /usr/include, MONALISA_INCLUDE_DIR-NOTFOUND)

SSLLIB         := /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, /usr/include)
SSLSHARED      := 

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

SHADOWFLAGS    := yes
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := yes
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := /mnt/vdb/lsf/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v5.34.34-cmake/lib/libgsl.a /mnt/vdb/lsf/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v5.34.34-cmake/lib/libgslcblas.a
GSLVERSION     := 

CINTMAXSTRUCT  := 
CINTMAXTYPEDEF := 
CINTLONGLINE   := 

BUILDCLING     := no
LLVMCONFIG     := 

BUILDCINTEX    := yes

BUILDREFLEX    := yes

BUILDROOFIT    := yes

BUILDMINUIT2   := yes

BUILDUNURAN    := yes

BUILDVC        := 
AVXCXXFLAG     := 
SIMDCXXFLAGS   :=  
VCFLAGS        :=  

BUILDVDT       := 

BUILDGDML      := yes

BUILDTABLE     := yes

BUILDTMVA      := yes

BUILDAFDSMGRD  := 
AFDSMGRDAPMON  := 

BUILDHTTP      := yes
USEFASCGI      := 
FASTCGIINCDIR  := 
ifeq ($(USEFASCGI), no)
FASTCGIFLAGS   := -DHTTP_WITHOUT_FASTCGI
endif

CPPUNIT        := 
GCCXML         := 

ROOTDICTTYPE   := cint

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

ROOTDRPMREL    := 1
